COVESA/dlt-viewer

qdlt/qdltmsg.cpp
=> Control response message always report ok

qdlt/qdltmsg.cpp
=> getloginfo payload content is missing the last byte

src/mainwindow.cpp
=> Remove null termination from injection message

INSTALL.txt, README.md
This just adds to the docs with specifics to building on MacOS.
=> Added infos on how to build on MacOS

src/dlt_viewer.desktop
Signed-off-by: Ravi Kandasamy Sundaram <ksr1122@gmail.com>
=> Fix exec name in dlt_viewer.desktop file

src/Darwin.cmake
Signed-off-by: Ravi Kandasamy Sundaram <ksr1122@gmail.com>
=> Fix cmake warning for Mac OS.

plugin/dltlogstorageplugin/dltlogstorageconfigcreatorplugin.cpp, plugin/dltlogstorageplugin/logstorageconfigcreatorform.cpp, qdlt/dlt_common.c
Signed-off-by: Ravi Kandasamy Sundaram <ksr1122@gmail.com>
=> Fix self assigned variable warning

src/ecudialog.cpp, src/ecudialog.h, src/mainwindow.cpp, src/mainwindow.h, src/project.cpp, src/project.h
Signed-off-by: Ravi Kandasamy Sundaram <ksr1122@gmail.com>
=> Fix udp port saving & loading

.gitignore
Signed-off-by: Olaf Dreyer <olaf.dreyer@partner.magna.com>
=> Ignoring *.orig backup files from KDiff3

plugin/dummyviewerplugin/dummyviewerplugin.cpp, qdlt/qdltfile.cpp, src/mainwindow.cpp
Fix Dlt Viewer seg fault when dummy viewer is enabled manually
=> Fix Dlt Viewer seg fault when dummy viewer is enabled manually

src/mainwindow.cpp
=> Fix Search Completer not working case insensitive

README.md
Update README.md with Build status link.
=> Update README.md with Build status

src/mainwindow.cpp, src/mainwindow.ui
Allow to search a filter by a piece of the name in the defaultfilter
combobox.
Fixeds #127
=> Combo Box for default filter is capable of search

src/dltuiutils.cpp
Improved the selection of the text color based on the background. Also
fixed calculation (the real value has been used for red rather than the
uint8 value).
=> Using better threshold for text color

README.md, build_parser_windows_qt5_MSVC.bat, build_qwt_windows_qt5_MSVC.bat, build_sdk_windows_qt5_MSVC.bat
=> Update to Qt version 5.12.10

README.md
=> Add Reference in README.md to additional plugin

src/mainwindow.cpp
=> Fix Filter Log Level Min Max enabled by mistake.

src/mainwindow.cpp
=> Fix serial connect problem

src/searchtablemodel.cpp, src/searchtablemodel.h, src/tablemodel.cpp, src/tablemodel.h
=> Fix colors in search table model and table model

ReleaseNotes_Viewer.txt, src/version.h
=> Prepare v2.21.0 Release

src/tablemodel.cpp
=> Fix index out of range issue

BuildDltViewer.pro
But it's not working.
Maybe someone knows, what's wrong here
The idea is to have a proper icon here
=> [WIP] attempt to fix icon for macOS

qdlt/qdltfile.cpp
Please check Issue #115 for more details.
Signed-off-by: Andrei Rusu <andrew_x_2005@yahoo.com>
=> Fix read of DLT with DLT header in payload

src/searchtablemodel.cpp
=> Fix no update of empty search table

src/mainwindow.cpp
=> Fix selection problem when index column not visible

build_sdk_windows_qt5_MSVC.bat
=> Pause build windows on desktop when finished

.github/dependabot.yml
See details here https://dependabot.com/
=> Introdcue Dependabot to keep actions up to date

.github/workflows/BuildPR.yml
First it has to be on master, all following pull request will build merge to master as well
=> Build merge to master

.github/workflows/BuildPR.yml
It's related to https://github.com/GENIVI/dlt-viewer/issues/172#issuecomment-781324586
=> Make Linux artifact executable

.github/workflows/BuildPR.yml
=> Remove Windows warning

.github/workflows/Release.yml, cabDir.bat
Current open issues:
* **Windows** is missing. When someone shows me how to zip release with board tools, I can make an additional pull request. I made a approach, but I failed
* **macOS** is not able to start. It needs to be signed, but I have no Apple developer account 
You can see an example here https://github.com/hannesa2/dlt-viewer/releases/tag/0.0.18 with artifacts.
=> Release action

.github/workflows/BuildPR.yml, .github/workflows/Release.yml, scripts/install.sh
brew install now qt 6 by default and build fails on my local machine
=> Use qt 5 on macOS

.github/workflows/BuildPR.yml
=> Reduce macOS builds

plugin/examples/filetransferplugin_configuration.xml, plugin/filetransferplugin/configuration.cpp, plugin/filetransferplugin/configuration.h, plugin/filetransferplugin/filetransferplugin.cpp
=> Removed App Id from Filetransfer Plugin

src/mainwindow.cpp
Signed-off-by: Alexander Wenzel Alexander.AW.Wenzel@bmw.de
=> Remove using default filter index

src/tablemodel.cpp
=> Increased priority of manual markers

src/mainwindow.cpp
=> Fix crash when TCP connection stopped and Serial connection available

src/mainwindow.cpp
=> Fix serial connection stopped when tcp disconnected

src/dltexporter.cpp
=> Keep whitespaces in ascii export

build_sdk_windows_qt5_MSVC.bat, plugin/dlttestrobotplugin/CMakeLists.txt, plugin/dlttestrobotplugin/dlttestrobotplugin.cpp, plugin/dlttestrobotplugin/dlttestrobotplugin.h, plugin/dlttestrobotplugin/dlttestrobotplugin.pro, plugin/dlttestrobotplugin/form.cpp, plugin/dlttestrobotplugin/form.h, plugin/dlttestrobotplugin/form.ui, plugin/plugin.pri, plugin/plugin.pro
=> Initial version of DLT Test Robot Plugin

src/ecudialog.cpp
=> Support more serial baudrates

src/filtertreewidget.cpp, src/filtertreewidget.h, src/mainwindow.cpp, src/mainwindow.h
* add "Filter Clear all" option to Filter table context menu
* support deleting all selected filters (multi-selection support)
* support deleting all selected filters with the DELETE key
Signed-off-by: Jens Schmer <jens.schmer@garmin.com>
=> User experience enhancements for filters

src/mainwindow.cpp
=> Remove unnecessary connect and disconnect during reload log file

build_config.bat, build_parser_windows_qt5_MSVC.bat, build_qwt_windows_qt5_MSVC.bat, build_sdk_windows_qt5_MSVC.bat, build_sdk_windows_qt5_MSVC_cmake.bat
=> Central config for all Windows batch files

ReleaseNotes_Viewer.txt, qdlt/qdltsettingsmanager.cpp, src/mainwindow.cpp, src/searchtablemodel.cpp, src/tablemodel.cpp, src/version.h
Fix compiler warnings
Fix settings integrity validation
=> Prepare v2.22.0

CMakeLists.txt, build_config.bat, build_qwt_windows_qt5_MSVC.bat, build_sdk_windows_qt5_MSVC_cmake.bat
=> CMake Windows Build improvements

src/dltexporter.cpp
=> Fix export to clipboard sometimes incomplete

qdlt/qdltfile.cpp, qdlt/qdltsettingsmanager.cpp, qdlt/qdltsettingsmanager.h, src/dltfileindexer.cpp, src/dltfileindexer.h, src/mainwindow.cpp, src/settingsdialog.cpp, src/settingsdialog.h, src/settingsdialog.ui
=> Local Index directory instead of global directory.

src/CMakeLists.txt, src/mainwindow.cpp, src/mainwindow.h, src/mainwindow.ui, src/sortfilterproxymodel.cpp, src/sortfilterproxymodel.h, src/src.pro, src/version.h
Explore dlt related files from Project view
=> Add file explorer feature

scripts/linux/install.md, scripts/linux/linuxdeploy.cmake.in, src/cmake/Linux.cmake, src/resources/dlt-viewer.desktop, src/resources/org.genivi.DLTViewer.desktop, src/src.pro
Some cleanups after commit 08b09b35bb2e421e8e6bae4f061640a12be4d9e6.
=> Linux scripts cleanups

src/mainwindow.cpp
=> Fix udp performance

src/ecudialog.cpp, src/ecudialog.h, src/mainwindow.cpp, src/mainwindow.h
=> Improve selection of serial port

src/ecudialog.cpp, src/ecudialog.h, src/mainwindow.cpp, src/project.h
=> Select UDP interface by interface name instead of IP address

src/main.cpp, src/mainwindow.cpp, src/project.cpp, src/searchdialog.cpp, src/searchdialog.ui, src/searchtablemodel.cpp, src/tablemodel.cpp
I've been using this for quite a while now and didn't have any issues so far.
The dark mode is activated with the UI settings in Windows.
=> Dark Mode for Windows + small QOL improvement

qdlt/qdltsettingsmanager.cpp, qdlt/qdltsettingsmanager.h, src/main.cpp, src/mainwindow.cpp, src/project.cpp, src/searchdialog.cpp, src/searchtablemodel.cpp, src/settingsdialog.cpp, src/settingsdialog.ui, src/tablemodel.cpp
Allow user to change the UI theme from settings dialog
=> Dark Mode - Add settings option to select UI colour

src/dltfileindexer.cpp, src/dltfileindexer.h, src/mainwindow.cpp, src/mainwindow.h, src/mainwindow.ui
=> Filter in selected Index Range

src/mainwindow.cpp
Signed-off-by: Manik Fulpagar [manik.fulpagar@ltts.com](mailto:manik.fulpagar@ltts.com)
=> Filter Range should Enabled/Disabled on Filter Enabled option

src/dltfileindexer.cpp
=> Fix filter range end

ReleaseNotes_Viewer.txt, src/version.h
Signed-off-by: Manik Fulpagar [manik.fulpagar@ltts.com](mailto:manik.fulpagar@ltts.com)
=> updated release note and version file to prepare for release

qdlt/qdltmsg.cpp, qdlt/qdltmsg.h, src/dltfileindexerthread.cpp, src/mainwindow.cpp
=> Fix QString from QByteArray length error with Qt6

qdlt/qdltsettingsmanager.cpp, src/settingsdialog.ui
=> Fix Settings Maximum file size cannot be changed anymore #340

qdlt/qdltsettingsmanager.cpp, qdlt/qdltsettingsmanager.h, src/mainwindow.cpp, src/settingsdialog.cpp, src/settingsdialog.ui
Temporary files were not saved before.
=> Add new option to save temporary file on exit.

src/mainwindow.cpp
=> Fix crash when right click on Explorer tab in some specific empty area (#345)

plugin/dlttestrobotplugin/dlttestrobotplugin.cpp, plugin/dummycontrolplugin/dummycontrolplugin.cpp, qdlt/export_rules.h, src/dltmsgqueue.cpp, src/mainwindow.cpp, src/src.pro
These functions were introduced in Qt 5.14
- Qt::endl https://doc.qt.io/qt-5/qt.html#endl
- QAtomicInt::loadRelaxed https://doc.qt.io/qt-5/qatomicinteger.html#loadRelaxed
Signed-off-by: Shinhoon Kang <asgawa@gmail.com>
=> Add qt version define comparison

INSTALL.md
=> bugfix: install qt5 dev packages manually since qt5-default is not available

src/dltfileindexer.cpp, src/dltfileindexer.h, src/mainwindow.cpp
when plugins and filters are disabled.
=> Improved speed when loading DLT files

.github/release.yml, .github/workflows/Release.yml
The plan is that all pull request are mentioned in release change log
=> Release with auto. generated changelog

.github/workflows/BuildPR.yml, .github/workflows/Release.yml
This reverts commit e379008b42beb2efc68b7f488cc655037ec0c6af.
Please see https://github.com/COVESA/dlt-viewer/pull/385/files#r1387107852
=> Revert "Bump jurplel/install-qt-action from 3 to 4 (#385)"

qdlt/qdltfilter.cpp, src/searchdialog.cpp
in filter and search, otherwise surprising behavior if payload contains newline chars
=> Dot matches newlines in regexps

qdlt/qdltoptmanager.cpp, qdlt/qdltoptmanager.h, src/workingdirectory.cpp
Simplifies working from commandline when required files are in current directory.
=> Set working directory from cli

plugin/filetransferplugin/filetransferplugin.cpp, src/filterdialog.cpp, src/filterdialog.h, src/filterdialog.ui, src/mainwindow.cpp, src/mainwindow.h, src/mainwindow.ui
- Filter configuration
- Filetransfer plugin
- Default filter selection
=> Fix Qt6 issues

build_config.bat, src/CMakeLists.txt, src/dltimporter.cpp, src/dltimporter.h, src/mainwindow.cpp, src/mainwindow.h, src/mainwindow.ui, src/src.pro
New file/class for import functions.
Add Visual Studio Professional support.
=> First MF4 import support.

qdlt/qdltoptmanager.cpp, qdlt/qdltoptmanager.h, src/dltimporter.cpp, src/dltimporter.h, src/mainwindow.cpp, src/mainwindow.h, src/mainwindow.ui, src/tablemodel.cpp
Mf4 Import: Check record ids.
Drag and Drop multiple pcap and mf4 files.
Explorer tab pcap and mf4 loading support.
=> Improve pcap and mf4 import.

src/dltimporter.cpp, src/dltimporter.h, src/mainwindow.cpp, src/mainwindow.h, src/mainwindow.ui
Multiple files in open dialog now possible.
Single import command for pcap and mf4.
=> Pcap and mf4 import improved Exlplorer widget support.

qdlt/qdltfile.cpp, qdlt/qdltfile.h, qdlt/qdltsettingsmanager.cpp, qdlt/qdltsettingsmanager.h, src/mainwindow.cpp, src/settingsdialog.cpp, src/settingsdialog.ui
Cahce size can be changed in the settings.
Improves GUI Response speed already with small cache size. Improves filter and search speed when cache size is set to bigger value.
=> New DLT Msg Cache.

src/dltimporter.cpp, src/dltimporter.h, src/mainwindow.cpp, src/settingsdialog.ui
Import DLT from PLP in pcap.
Fix DLT Import from IP Segmentation
=> Fix import from pcap file dialog.

qdlt/qdltfile.cpp, qdlt/qdltfile.h
- do not cache when DLT message is corrupted
- disable when cache size set to 0.
=> Fix Cache function:

README.md, qdlt/qdltoptmanager.cpp, qdlt/qdltoptmanager.h, src/main.cpp, src/mainwindow.cpp
Explicit terminal command in command line.
Terminate command line only when terminate command used. Multiple Filter per command line.
Combination of Import and Convert now possible.
Reorder command line commands.
=> Clean up convert command line command.

src/mainwindow.cpp, src/mainwindow.h, src/mainwindow.ui
Integration of PCAP/MF4 Import into Open/Append command.
=> Further Cleanup Open and Append commands.

src/dltexporter.cpp, src/ecudialog.cpp, src/ecudialog.ui, src/searchtablemodel.cpp, src/tablemodel.cpp
Added Baudrate 1000000 to serial port.
=> Change Export to simplified payload.

src/ecudialog.ui, src/plugindialog.cpp
Allow loading multiple configuration files in one plugin separated by |.
=> Fix baudrate disabled.

plugin/examples/filetransferplugin_configuration.xml, plugin/filetransferplugin/configuration.cpp, plugin/filetransferplugin/configuration.h, plugin/filetransferplugin/file.cpp, plugin/filetransferplugin/filetransferplugin.cpp, plugin/filetransferplugin/filetransferplugin.h, plugin/filetransferplugin/form.cpp, plugin/filetransferplugin/form.h
- Copy ID and filename in context menu
=> Filetransfer Plugin: - Default Save path

qdlt/qdltfile.cpp, qdlt/qdltfilterlist.cpp, src/tablemodel.cpp
=> Fix dark mode.

.github/release.yml, INSTALL.md, scripts/darwin/build.sh
It's just some build cosmetic to prepare for arm64 build
=> MacOS build more verbose

scripts/darwin/build.sh
updated qt for arm64
Still need to verify if "qmake" will work for arm64
=> MacOS qt5 arm64 cmake solution

INSTALL.md, build_config.bat, src/mainwindow.cpp, src/mainwindow.h, src/mainwindow.ui
=> Fix Multifilter feature, expecially with older Qt version.

src/main.cpp, src/mainwindow.cpp, src/searchdialog.cpp, src/searchdialog.h
The removed function is not used anywhere
=> Remove unused code and silence a deprecation warnings

src/dltfileindexer.cpp, src/mainwindow.cpp
Reduce command line dlt file load progress update.
=> Fix filter menu.

.github/workflows/Release.yml
It looks good https://github.com/COVESA/dlt-viewer/actions/runs/9954103685
=> Fix release job

qdlt/CMakeLists.txt, qdlt/dlt_common.c, qdlt/qdlt.pro, src/mainwindow.cpp
Enable plugins if disabled when pre command called.
=> Revert Rename of dlt_common.

INSTALL.md, README.md
Adding link to Mac Appstore to Readme.md and Install.md
=> Mac app store

src/searchdialog.cpp, src/searchdialog.h, src/searchdialog.ui
https://github.com/COVESA/dlt-viewer/issues/502
As mentioned in the issue, this functionality has been broken for long time and as such is unusable and unused.
=> Remove dead code related to payload range search functionality

.github/workflows/BuildPR.yml, .github/workflows/Release.yml
It's about to have a x86 and an arm64 version for MacOS
=> Abi in MacOS artifacts

.github/workflows/BuildPR.yml
=> Notarization (copy)

.github/workflows/BuildPR.yml
=> Skip notarization on a fork

.github/workflows/Release.yml
It's hard to test a release without making a release, so I will create a new release
close #547
=> Fix MacOS release artifacts

.github/workflows/Release.yml
=> MacOS release with codesign and notarization

.github/workflows/Release.yml
=> Include mac artifacs release

qdlt/qdltimporter.cpp, qdlt/qdltimporter.h
Enable MF4 import of multiple data frames.
=> Improve speed of MF4 and PCAP import.

qdlt/qdltexporter.cpp
This causes currently issues with non verbose messages.
=> Revert/Remove Regex Replace feature for DLT Export.

scripts/linux/build.sh
related to  #557 
@alexmucde I'm not sure about complete delete or to comment it
=> Linux build only with cmake in CI

commander/main.cpp, qdlt/qdltexporter.cpp, src/dltfileindexer.cpp, src/mainwindow.cpp
Fix add multiple filter to dlt commander.
Enable filter when providing a filter file by the commandline.
=> Improve progress output.

qdlt/CMakeLists.txt, qdlt/qdltfile.cpp, qdlt/qdltfile.h, qdlt/qdltfilter.cpp, qdlt/qdltfilter.h, qdlt/qdltfilterlist.cpp, qdlt/qdltfilterlist.h, qdlt/qdltlrucache.hpp, src/tablemodel.cpp, src/tablemodel.h
This significantly simplifies code for the Qt-model, by making the intent clear and code better structured. Moreover, this most probably avoids redundant decodings and encodings
=> LRU for main table model

commander/main.cpp, qdlt/qdltimporter.cpp, qdlt/qdltimporter.h, src/mainwindow.cpp, src/mainwindow.h
Improve progress bar for import.
=> Background thread for import.

commander/main.cpp, qdlt/qdltexporter.cpp, qdlt/qdltexporter.h, src/mainwindow.cpp, src/mainwindow.h
Improve progress bar for Export.
=> Background thread for export.

qdlt/dltmessagematcher.cpp, qdlt/tests/test_dltmessagematcher.cpp
https://github.com/COVESA/dlt-viewer/issues/616
It was probably a copy-paste issue
=> Fix incorrect matching algo

scripts/linux/linuxdeploy.cmake.in
https://github.com/COVESA/dlt-viewer/issues/624
=> install required offscreen plugin into appimage

src/mainwindow.cpp, src/mainwindow.h, src/tablemodel.cpp, src/tablemodel.h
Implementation of Tooltip for timestamp and time
Signed-off by : Pavithra Anand <Pavithra.AA.Anand@partner.bmwgroup.com>
=> Distinguish Log Generation and Storage Timestamps

src/mainwindow.cpp
Improved the visibility of scrollbar in dark mode.
Signed-off by : Pavithra Anand <Pavithra.AA.Anand@partner.bmwgroup.com>
=> Improve Dark Mode Visibility of Scrollbar

src/mainwindow.cpp, src/mainwindow.h
Shortcut implementation for mark/unmark lines
Signed-off by : Pavithra Anand <Pavithra.AA.Anand@partner.bmwgroup.com>
=> Mark and Jump To Messages

src/mainwindow.cpp, src/mainwindow.h
Shortcut implementation for Copy message payload
Signed-off by : Pavithra Anand <Pavithra.AA.Anand@partner.bmwgroup.com>
=> Copy Message Payload

.github/workflows/BuildPR.yml, .github/workflows/Release.yml
remove Ubuntu 20.04 from PR and Build.
Replace Ubuntu 20.04 with 22.04 and 24.04 in Release
=> Remove ubuntu 20.04

commander/dltfileexporter.cpp
Additionally fix the SimpleWriter by opening a file
https://github.com/COVESA/dlt-viewer/issues/688
=> Fix regexp replace functionality in commander

.gitignore, CMakePresets.json
Added CMakePresets.json since most IDEs can already parse it for easy configuration
=> add cmake presets and update gitignore

.github/workflows/BuildPR.yml, .github/workflows/Release.yml
=> Fix Windows release pipeline
