- README.md
The mailing list URL have unfortunately changed slightly.  The wiki page
URL is unchanged, but the link is now more nicely formatted.
> README: Fix links to mailing list and wiki page

- INSTALL.txt
The way the source path was referred to was ambiguous as there is an src/ folder inside the repository which contains a (non-top-level) CMakeLists.txt. User would be easily confused and point to this folder instead of the root folder with the top level CMakeLists.txt.
> Changed ambiguous wording in documentation for CMake builds

- plugin/dltdbusplugin/dltdbusplugin.cpp
- plugin/dltdbusplugin/dltdbusplugin.h
- plugin/dummycontrolplugin/dummycontrolplugin.cpp
- plugin/dummycontrolplugin/dummycontrolplugin.h
- plugin/filetransferplugin/filetransferplugin.cpp
- plugin/filetransferplugin/filetransferplugin.h
- qdlt/plugininterface.h
- qdlt/qdlt.h
- qdlt/qdlt.pro
- qdlt/qdltmessagedecoder.cpp
- qdlt/qdltmessagedecoder.h
- qdlt/qdltplugin.cpp
- qdlt/qdltplugin.h
- qdlt/qdltpluginmanager.cpp
- qdlt/qdltpluginmanager.h
- src/mainwindow.cpp
- Add possibility to inject message decoder facade into the
plugin
Motivation: allow plugin to decode messages, which it retrieves
from the QDltFile.
- Add possibility to inject main table view into the
plugin
Motivation: allow plugin to scroll main table view to a certain
row
- Add possibility to notify the plugin about the changed
configuration
Motivation: plugin should be able to reset its analysis
data in case of changed configuration
- Extend comments of QDltPluginViewerInterface::initMsg &
QDltPluginViewerInterface::initMsgDecoded methods in order to
reflect its cross-thread calling nature
All done changes were tested on a
self-made plugin.
Decoding of messages works as expected
Scrolling of
main table works as expected
Reaction on certain configuration-change
use-cases works as …
> Extension of QDltPluginControlInterface with new notification events

- INSTALL.txt
Use `qmake` instead of `qmake-qt5` in Linux install instructions. 
Because `qt5-default` doesn't install `qmake-qt5`, but `qmake` .
Test environment: ubuntu 18.04 LTS
> Update INSTALL.txt 

- src/searchtablemodel.cpp
While working with the DLT-Viewer I realized that it would be a good idea to have the marker colors in the search table.
It's a little hacky and copy&paste-y but it works.
It would be a good idea to implement markers in the parent class of tablemodel and searchtablemodel.
> added marker colors to searchtablemodel

- src/Darwin.cmake
Added `Info.plist` configuration on the post-build stage.
According to [Qt Documentation - High DPI Displays](https://doc.qt.io/qt-5/highdpi.html) the high-DPI support is enabled by settings in `Info.plist` file by adding `NSPrincipalClass - NSApplication` and `NSHighResolutionCapable - true`.
Without the high-DPI configuration the DLT Viewer app looks bad on the Retina and higher displays.
**High DPI Support Disabled**
**High DPI Support Enabled**
> High DPI Displays Support on macOS

- src/src.pro
Corrected the `rpath` option for macOS
The macOS uses the Clang compiler. The [`rpath` syntax for Clang](https://clang.llvm.org/docs/ClangCommandLineReference.html#cmdoption-clang-rpath) differs from GCC.
- Clang: -rpath <arg>
- GCC: -rpath=dir
The change was introduced due to the build failing with error:
```
ld: unknown option: -rpath=.
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
> Fix: macOS qmake build

- .ci/travis/build.sh
- .ci/travis/install.sh
- .travis.yml
Added Travis CI support
Build Matrix includes the following systems:
- Ubuntu 16.04 (Xenial)
- Ubuntu 18.04 (Bionic)
- macOS 10.13 (High Sierra)
- macOS 10.14 (Mojave)
During each job, the CMake and QMake builds are performed
**Notes:**
* For setup, the repository should be activated on https://travis-ci.org (Free Travis for Open Source projects)
* Currently, the macOS QMake build is broken, so the Xcode jobs will be marked as failed. The fix: [GENIVI/dlt-viewer/pull/96](https://github.com/GENIVI/dlt-viewer/pull/96)
**Motivation:**
The DLT Viewer repository has the configured CI for the Windows platform but lacks support for Linux and macOS. The further maintaining and development will be easier if all supported platforms will be built during the CI process.
> Feature: Travis CI Support

- qdlt/qdltfilter.cpp
- Fix inverted condition when setting pattern options.
- Fix incorrect passing of case sensitivity flag as match offset which prevented the ^ anchor from working.
> Fix case insensitive regexp match in filters

- qdlt/qdltfile.cpp
- qdlt/qdltfile.h
Change description:
- Addition of the QDltFile::getFileMsgNumber method, which allows to get number of messages of the underlying file object
Verification criteria:
- Build tested locally on Windows and Linux
Signed-off-by: Vladyslav Goncharuk <svlad1990@gmail.com>
> Introduction of the QDltFile::getFileMsgNumber method

- src/CMakeLists.txt
Use the destination variables defined in the toplevel CMakeLists instead
of the hardcoded "deploy" directory. This makes the "install" target
behave in the standard CMake way, i.e. allows to relocate the whole
installation tree using CMAKE_INSTALL_PREFIX and find the binaries in
the expected place.
Signed-off-by: Oleg Kolosov <bazurbat@gmail.com>
> Fix non-standard binary install destination

- src/mainwindow.cpp
1. Do not raise search results panel every time the filters are updated
If the user explicitly hid it they most likely prefer to keep it hidden. The panel will still be shown when the "FindNext" action is activated.
2. Sync view menu checkboxes with restored window state
When the application is restarted the visibility state of the dock widgets does not reflect the checkboxes in the View menu. This will require activating menu items twice to make them in sync.
> Fix dock widgets hide restore

- CMakeLists.txt
- Introduction of wrapping GCC specific flags into "not MSVC" condition to avoid build fail for MSVC CMake build
- Build tested locally on Windows
- All sanity checks passed for Linux and Windows builds: https://github.com/svlad-90/DLT-Message-Analyzer/runs/1038659363
Signed-off-by: Vladyslav Goncharuk <svlad1990@gmail.com>
> [ISSUE #113][Bug] CMake build is not supported for MSVC

- INSTALL.txt
Change description:
- Updated the INSTALL.txt for build instructions for release version using qmake on MacOs
Verification criteria:
- Build on MacOs Catalina Version 10.15.3(19D76) and checked
Signed-off-by: Fani Bhushan <bhufani@gmail.com>
> [ISSUE #87] Plugins are not working on Mac

- src/main.cpp
Qt requires these attributes set after the creation else it will stay
blurry on macOS.
> Set scaling attributes after create QApplication

- qdlt/qdltdefaultfilter.cpp
- qdlt/qdltdefaultfilter.h
Enabled the loading of .dlf from subfolders within the default filter
location. Symlinks are also allowed.
Fixes #126
> Load dlf from subfolders

- src/mainwindow.cpp
- src/project.cpp
If a corrupted file has been passed to LoadFilter it still tried to load
the filters after notifying the loading of the file failed. This caused
a crash. Also the duplicate Messagebox has been removed.
Signed-off-by: Matthias Bilger <matthias@bilger.info>
> Fix filter load in case of error

- src/mainwindow.cpp
- src/mainwindow.h
Fixed scroll in table view in case when Index column is hidden; 
Disabled autoscroll to the right in search results
Signed-off-by: Andrey Sakun sakun.andrey@gmail.com
> Fixed scroll in table view in case when Index column is hidden

- src/dltfileindexer.cpp
- src/dltfileindexer.h
- src/dltfileindexerthread.cpp
- src/dltfileindexerthread.h
For messages that have the exact same time/timestamp, we keep the same order for the messages by using their index.
Fixes #124
**This has not been tested**. @alexmucde if you can help with a test build it would be great.
> Sort by time/timestamp keeps index order

- src/mainwindow.cpp
- src/mainwindow.ui
If the checkbox is activated and default filter is selected it is
appended rather than replacing the previous filters.
Fixes #128
> Enable optional append for default filters

- CMakeLists.txt
Currently there is no build type set resulting in neither optimization
nor debug settings enabled. This applies to single configuration
generators that are the default on Linux systems.
Set to Release by default to get an optimized build. This results in
much higher performance and is therefore a good default for most
regular users.
> Set default CMAKE_BUILD_TYPE for single configuration builds

- .travis.yml
Btw, you will observe errors is all macOS builds, but the job is successful.
I'm not sure if this is the desired behavior
> Build on macOS Big Sur

- INSTALL.md
I recommend not to explain git fundamental basics, btw the commands are wrong, they should be swapped.
Conclusion: it's just noise
> Remove wrong (swapped) clone commands for macOS

- qdlt/qdltconnection.cpp
- qdlt/qdltconnection.h
- qdlt/qdltmsg.cpp
- qdlt/qdltmsg.h
- src/ecudialog.cpp
- src/ecudialog.ui
- src/mainwindow.cpp
- src/project.cpp
- src/project.h
- src/version.h
Provide a new connection type "Serial ASCII" for serial ASCII terminals. All received lines over a serial line are converted and written into DLT message into the currently opened DLT file. Select Interface Type "Serial ASCII" in the ECU configuration.
> New Connection type Serial ASCII

- doc/dlt_viewer_user_manual.tex
Since commit b0d4db8de36ed3f5a8cbff32bcd05ddf4742589e the executable name is dlt-viewer.
Fallout from commit 0e6539e2a5ec6a3d3e5bbb2360463328073e70ea.
> doc: Fix executable name

- .github/workflows/Release.yml
With this pull request the Windows artifacts are kept as well
https://github.com/hannesa2/dlt-viewer/releases/tag/v2.21.2.0
> Keep windows artifacts

- CMakeLists.txt
Make the usage of RPATH settings to detect non-standard QT
installations optional.
> Disable RPATH usage:

- src/dltexporter.cpp
- src/mainwindow.cpp
- Allow the user to use the copied payload directly without the need to remove the newline every time.
- The payload of a message can be used to search in code or in DLT logs.
- The title of the search results window doesn't contain results count when the search is triggered from the icon buttons next to the search text box.
- Somehow the signals are triggered differently when the search is triggered from the icon buttons.
> Minor refactoring at mainwindow and DltExporter 

- parser/mainwindow.cpp
I'm using dlt-parser with automated scripts, so I had removed progress bar that was shown even in "--no-gui" option was set
> Hide "parse directory" progress bar when "--no-gui" option is used

- build_sdk_windows_qt5_MSVC.bat
- build_sdk_windows_qt5_MSVC_interactive.bat
Apparently, there are problems setting the errorlevel
variable after rmdir was called and if errorlevel is
checked afterwards it will be always reported as 0,
although there were errors when deleting the directories/files.
Executing the "rem" command on error works around this
issue. For details see https://stackoverflow.com/a/11137825
Also, remove user prompts and exit only the current script
(exit /b) instead of the whole cmd process to let users call
this script from other scripts for automation purposes for
example.
Signed-off-by: Jens Schmer <jens.schmer@garmin.com>
> Windows build script improvements

- qdlt/qdltargument.cpp
The DLT_TYLE info was missing for bool types. Added the TYLE in similar
way as for Ints or Floats.
Issue: #242
> fix: persist bool args with DLT_TYLE_8BIT

- src/mainwindow.cpp
With serial ascii mode we can use dlt viewer as a powerful serial debugging tool, the only missing part is the serial sending ability.
> Add plain serial sending ability for send injection on serial ascii mode

- qdlt/qdltpluginmanager.cpp
- qdlt/qdltpluginmanager.h
- qdlt/qdltsettingsmanager.cpp
- qdlt/qdltsettingsmanager.h
- src/mainwindow.cpp
- src/mainwindow.h
- src/mainwindow.ui
- src/plugintreewidget.cpp
- src/plugintreewidget.h
- src/project.cpp
- src/project.h
Currently, the execution sequence of DLT Plugins depends on the discovery/loading order.
According to QDir documentation, all plugins in a certain plugin folder are discovered/loaded alphabetically, but DLTViewer supports more than one plugin folder.
Some Plugins might require some others to be executed before (e.g. in most/some cases it could make sense that Decoder plugins are executed before Viewer Plugins)
This pull request allows the user to set a custom execution sequence for the DLT Plugins and store it in the project file. The plugins can be reordered by:
* context menu
* drag and drop
* dedicated buttons
General/DLT Viewer plugin execution sequence can also be modified in the settings file. However, new execution sequence is not stored automatically when closing the application.
> Enable to set a custom execution sequence for DLT Plugins

- .github/workflows/Release.yml
A few minor changes to the MacOS job, so it succeeds, and the artefacts can be uploaded.
It now works on my fork (when a tag is pushed): https://github.com/agravgaard/dlt-viewer/actions/runs/2956350864.
Putting the assets on one line may not be necessary; I can drop that commit if you prefer.
> Fix: Release pipeline

- src/dltexporter.cpp
- src/dltexporter.h
- src/mainwindow.cpp
- src/mainwindow.h
Added feature to export selected Dlt messages as Jira table via clipboard. This is possible in main message table as well as in search table.
* tested on Windows (MSVC 2019) 
Signed-off-by: Sven Lübke [sven.luebke@mikrosol.de](mailto:sven.luebke@mikrosol.de)
> Added feature to export (selected) Dlt messages as Jira table via clipboard

- qdlt/qdltpluginmanager.cpp
- Changed the 'pMutex_pluginList' to work in the recursive mode
Signed-off-by: Vladyslav Goncharuk <svlad1990@gmail.com>
> [ISSUE #292] Fix dead-lock in the dltpluginmanager

- scripts/darwin/package.cmake
Darwin script still references Qt5 rather than Qt6. Changed to Qt6:moc
> Fix build fail on Darwin.

- qdlt/qdltconnection.cpp
This approach is working on macOS arm64 architecture.
> No viable conversion from 'QDltDataView' to 'QByteArray'

- src/mainwindow.cpp
Fix usage of two separate calls to determine seconds and microseconds. Replaced by single timespec_get call.
Fixed as well a race condition where provided sec or usec to writeDLTMessageToFile are 0.
Issue: #232
> Fix non-monotonic timestamps under Windows

- src/mainwindow.cpp
Allows for faster mouseless usage
* Ctrl-L to focus search window
* Ctrl-Shift-A to add open add filter dialog
* Ctrl-Shift-C to apply filters
> Add more keyboard shortcuts

- qdlt/qdltoptmanager.cpp
- qdlt/qdltoptmanager.h
- src/mainwindow.cpp
Treat all arguments with dlt ending that are not used up by another option as log files. Sort multiple files by name to guarantee consistent behavior.
\+ Add missing help text for passing dlt file(s) only
> Allow passing multiple dlt files on commandline

- plugin/nonverboseplugin/nonverboseplugin.cpp
- plugin/nonverboseplugin/nonverboseplugin.h
- Show progress Bar when loading Fibex files
- Improve decoding speed
- Show only ID in Project/Plugin tree
> Improve non verbose mode plugin:

- qdlt/qdltoptmanager.cpp
Decide which one it is based on extension. Simplifies usage from command line when dlt and project files are grouped in directories.
> Allow mixing project and dlt file arguments directly

- README.md
- qdlt/qdltoptmanager.cpp
- qdlt/qdltoptmanager.h
- src/mainwindow.cpp
Log files, project file and filter file can now be loaded in commandline without option.
Remove old commands -l, -p, -f.
Multiple plugin commands at once now possible.
New option -b to execute plugin commands before loading log file. Update command line documentation.
> Improve and document command line options

- scripts/darwin/install.sh
Latest QT5 brew release 5.15.13 fails to install dependencies
> macOS: Fix build with brew QT5.15.13

- INSTALL.md
- README.md
- build_config.bat
- plugin/filetransferplugin/filetransferplugin.cpp
- src/mainwindow.cpp
Update build script to Qt6.6.2.
Update version info.
> Fix Filetransfer Plugin Qt6 issue.

- src/tablemodel.cpp
When logs are really long it's not possible to see all the contents. The easiest solution is to add simple tooltip to every log.
> Add tooltips to logs

- qdlt/qdltargument.cpp
- qdlt/qdltmsg.cpp
- src/dltexporter.cpp
Hello there, I'd like to start contributing to this project, here is a small patch where I'm just fixing compilation warnings
> Fixed some compilation warnings

- .github/workflows/BuildPR.yml
- scripts/darwin/build.sh
- scripts/darwin/install.sh
> MacOS qt5 arm64 build

- qdlt/qdltargument.cpp
- qdlt/qdltimporter.cpp
- qdlt/qdltmsg.cpp
- qdlt/qdltpluginmanager.cpp
- qdlt/qdltpluginmanager.h
- src/plugintreewidget.cpp
- src/plugintreewidget.h
- src/settingsdialog.cpp
Mainly due to deprecated methods and integer comparison of different signedness.
> Fix more compilation warnings

- qdlt/CMakeLists.txt
- qdlt/dlt_common.cpp
- qdlt/qdlt.pro
This makes sure c++ compiler is used and not plain c, failing with some error like
[ 10%] Building C object qdlt/CMakeFiles/qdlt.dir/dlt_common.c.o
cd /dlt-viewer/obj-x86_64-linux-gnu/qdlt && /usr/bin/cc -DBYTE_ORDER=LITTLE_ENDIAN -DPLUGIN_INSTALLATION_PATH=\"/usr/lib/x86_64-linux-gnu/dlt-viewer/plugins\" -DQT5 -DQT5_QT6_COMPAT -DQT_CORE_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_SERIALPORT_LIB -DQT_VIEWER -D_TTY_POSIX_ -Dqdlt_EXPORTS -I/dlt-viewer/obj-x86_64-linux-gnu/qdlt -I/dlt-viewer/qdlt -I/dlt-viewer/obj-x86_64-linux-gnu/qdlt/qdlt_autogen/include -I/dlt-viewer/qdlt/../src -isystem /usr/include/x86_64-linux-gnu/qt6/QtCore -isystem /usr/include/x86_64-linux-gnu/qt6 -isystem /usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -isystem /usr/include/x86_64-linux-gnu/qt6/QtNetwork -isystem …
> Rename dlt_common.c into dlt_common.cpp.

- commander/main.cpp
- commander/optmanager.cpp
- commander/optmanager.h
- qdlt/qdltexporter.cpp
- qdlt/qdltexporter.h
- qdlt/qdltoptmanager.cpp
- qdlt/qdltoptmanager.h
- src/mainwindow.cpp
Set dlt-commander export timezone to default.
> New command line option delimiter for CSV export.

- build_sdk_windows_qt5_MSVC.bat
- src/cmake/Windows.cmake
https://github.com/COVESA/dlt-viewer/issues/508
offscreen plugin is required since this change: https://github.com/COVESA/dlt-viewer/commit/990abade4cfc19d6c7500fb78673128b1377cc51
Probably using `windeployqt`-tool for packaging could have avoid this bug
> install qoffscreen plugin on windows

- src/mainwindow.cpp
MainWindow was set as a parent of the context menu actions as a result all actions ever created (upon each ctx menu open) in one program session remained on the heap until program is closed (it is basically some kind of resources leak). Assigning local menu variable as a parent deallocates actions when menu is closed
> change parent of actions in config context menu

- src/mainwindow.cpp
The QAbstractSocket::error signal existed in Qt<5.15, but was renamed to QAbstractSocket::errorOccured probably to avoid
https://stackoverflow.com/a/48250710
Since the codebase still uses the old style of connections the compiler could not detect that signal does not exist anymore and error was reported only on runtime:
"qt.core.qobject.connect: QObject::connect:
No such signal QTcpSocket::error(QAbstractSocket::SocketError)"
> fix signal for socket error

- qdlt/qdltoptmanager.cpp
If app is open with a double click, close the invoked console as before
https://github.com/COVESA/dlt-viewer/issues/517
> Keep console logging if app is launched from cmd

- src/mainwindow.cpp
Names of the signals changed between Qt 5.12 and 5.15, while we still need to maintain compatibility with 5.12
> Make code backward compatible with Qt 5.12

- scripts/darwin/build.sh
Reduce the size of macOS artifacts that are created during the build CI/CD pipeline.
Changes:
removed tar command from build as after notarization, binaries are tar'ed
> Removed creating tar from build

- .github/workflows/BuildPR.yml
- qdlt/CMakeLists.txt
- qdlt/tests/CMakeLists.txt
- scripts/linux/build.sh
- scripts/linux/install.sh
This adds a step into Linux pipeline to build and run unit tests
> Run unit tests for Linux on CI

- qdlt/qdltoptmanager.cpp
- qdlt/qdltoptmanager.h
- qdlt/tests/CMakeLists.txt
- qdlt/tests/test_dltoptmanager.cpp
- src/main.cpp
- src/mainwindow.cpp
As a side effect this PR removes some code duplication which had to be kept in sync + cmd parsing functionality is now handled by the Qt and the logic for combining those args is tested (at least those combinations that are given in examples)
> Use QCommandLineParser for command line args parsing

- qdlt/qdltexporter.cpp
- qdlt/qdltfile.cpp
- qdlt/qdltfile.h
- qdlt/qdltfilterlist.cpp
- qdlt/qdltfilterlist.h
- src/searchtablemodel.cpp
- src/tablemodel.cpp
RegEx Replace will only be executed when filter matches. Re enable RegEx Replace for DLT Export, no influence on non verbose messages anymore.
> Fix and Improve RegEx Replace feature.

- qdlt/qdltexporter.cpp
- qdlt/qdltoptmanager.cpp
- qdlt/qdltoptmanager.h
- qdlt/tests/CMakeLists.txt
- qdlt/tests/test_dltoptmanager.cpp
- src/main.cpp
- src/mainwindow.cpp
These PR contains part of changes from the reverted https://github.com/COVESA/dlt-viewer/pull/543. The changes for arg parsing arguments that [caused some issues](https://github.com/COVESA/dlt-viewer/pull/543#issuecomment-2404238471) are dropped until it is clear why they happen and how to fix them. 
The most important part of this PR is unit tests for QDltOptmanager, other changes are minor and should not affect the app functionality.
> Add QDltOptmanager unit tests and minor cleanup

- src/mainwindow.cpp
If user-typed filename does not have any extension.
This small UX improvement I decided to propose after spending some time to understand why "default filter functionality" does not work even though I placed the filter file into right folder. The cause was that I saved filter in a file without dlf-suffix
> Add dlf file extension when saving filter

- src/tablemodel.cpp
With this MR logging only mode is handled separately before any message decoding happens. Before this MR, although msg was default-assigned in one of the if-cases, it still was non-empty due to multiple decodings happening in the data-method for values of `role`-variable other than `DisplayRole`.
> Simplify handling of logging only mode in log table view

- qdlt/qdltoptmanager.cpp
- qdlt/qdltoptmanager.h
- qdlt/tests/test_dltoptmanager.cpp
- src/mainwindow.cpp
PR employs QCommandLineParser for parsing cmd args for dlt-viewer. As [requested](https://github.com/COVESA/dlt-viewer/pull/543#issuecomment-2404277299), in a followup PRs similar change can be applied to other cli tools developed in this repo.
The PR restores the previously reverted changes, that [reported to cause some issues](https://github.com/COVESA/dlt-viewer/pull/543#issuecomment-2404238471). Should remain unmerged until fix is found (but only after clear issue is reported) or we can merge it again and if issue is observed, request to create a bug ticket with clear description.
@alexmucde I would need your help to understand what kind of issues this causes and how to reproduce it. Unit tests can help to ensure workability of different cmd scenarious.
> Reapply "Use QCommandLineParser instead of custom cmd args parsing (#543)"

- src/dlttableview.cpp
- src/dlttableview.h
- src/mainwindow.cpp
- src/mainwindow.h
https://github.com/COVESA/dlt-viewer/issues/577
> Change table view font on Ctrl + Wheel combination

- src/dlttableview.cpp
The introduction of the Ctrl+Wheel combination broke the normal mouse table view scrolling. This fixes the issue
> Fix wheel scrolling of the main tableview

- src/dltfileindexer.cpp
- src/dltfileindexer.h
- src/mainwindow.cpp
- src/mainwindow.h
- src/project.cpp
- src/project.h
These are very minor improvements that I could so far make working on https://github.com/COVESA/dlt-viewer/issues/576
Nonfunctional changes, just some easy cleanups.
> Cleanup the code related to ECUs tree populating functionality

- CMakeLists.txt
- src/mainwindow.cpp
- src/src.pro
**Why:**
Without the missing includes, we had incomplete types.
**What:**
Added the necessary includes to resolve the incomplete types issue.
**Why:**
`dlt_common.c` includes `<QtGlobal>` which implicitly includes `<qtypes.h>`, which contains a `static_assert` that requires the C11 standard. This was causing issues with the GCC compiler, which does not support `static_assert` in earlier C standards.
**What:**
Explicitly set the C standard to C11 to ensure compatibility with the `static_assert` usage in the code.
> Fix compilation issues

- plugin/dlttestrobotplugin/dlttestrobotplugin.cpp
- qdlt/dlt_types.h
- qdlt/dlt_user.h
- qdlt/export_rules.h
- qdlt/qdltsegmentedmsg.h
- src/dltmsgqueue.cpp
- src/mainwindow.cpp
This c++ header is no longer in pure C-headers. This PR supersedes  https://github.com/COVESA/dlt-viewer/pull/513
> No use of QtGlobal in c-code

- .clang-format
- plugin/dltdbusplugin/dltdbusplugin.cpp
- plugin/dlttestrobotplugin/dlttestrobotplugin.cpp
- plugin/dlttestrobotplugin/dlttestrobotplugin.h
- plugin/filetransferplugin/filetransferplugin.cpp
- plugin/nonverboseplugin/nonverboseplugin.cpp
- qdlt/qdltplugin.cpp
- qdlt/qdltplugin.h
- qdlt/qdltpluginmanager.cpp
- qdlt/qdltpluginmanager.h
Mainly removal unnecessary heap allocations (use stack instead), redundant code removal, use of algos instead of raw loops
> Minor plugins refactoring

- parser/qdltparser.h
- qdlt/dlt_common.h
- qdlt/dlt_types.h
This reverts commit a3ad76c19cea1a52a8870d435e6cb4f1de4d2621.
> Decruft some old dead code from header files

- qdlt/CMakeLists.txt
- qdlt/qdlt.pro
- qdlt/qdltctrlmsg.cpp
- qdlt/qdltctrlmsg.h
- qdlt/tests/CMakeLists.txt
- qdlt/tests/test_dltctrlmsg.cpp
- src/CMakeLists.txt
- src/ecutree.cpp
- src/ecutree.h
- src/mainwindow.cpp
- src/mainwindow.h
- src/src.pro
This PR resolves https://github.com/COVESA/dlt-viewer/issues/576 for the cases when DLT log contains lots of apps and contexts. 
Historically, the same function used to populate ECU tree (in the "Config"-tab) both in online and offline modes. This was a problem for offline mode (aka dlt-file loading), because UI update is then called multiple time in a short time frame ate the end of file processing freezing the whole app. The fix is to:
1. Separate parsing of control messages payloads from UI creation
2. When tree view is created use more efficient constructors, which do not force many redundant UI updates.
> Do not block UI when building ECUs tree

- scripts/linux/install.md
Document the requirements for executing the AppImage.
See https://github.com/COVESA/dlt-viewer/issues/626 and https://github.com/COVESA/dlt-viewer/issues/622#issuecomment-2653646760.
> Document Dependencies for Executing AppImage

- src/mainwindow.cpp
Keep outputfile open, when first DLT message was written. Issue was introduced with 2024-01-31 feature opening ReadOnly DLT files.
> Fix performance issue with online tracing.

- commander/CMakeLists.txt
- commander/commander.pro
- commander/dltfileexporter.cpp
- commander/dltfileexporter.h
- commander/main.cpp
- commander/optmanager.cpp
- commander/optmanager.h
- qdlt/qdltfile.cpp
- qdlt/qdltfile.h
- qdlt/qdltfilterlist.cpp
- qdlt/qdltfilterlist.h
https://github.com/COVESA/dlt-viewer/issues/363
> Dlt files split

- qdlt/qdltargument.cpp
The default QString constructor uses internally fromUtf8 which is wrong for strings that claim to be ascii encoded.
Issue: #638
> fix: use fromLatin1 for string args with ascii encoding

- qdlt/qdltctrlmsg.cpp
- qdlt/qdltctrlmsg.h
- src/mainwindow.cpp
Set of control messages used to figure out ECUs tree is a subset of all possible control messages. Regression has been introduced https://github.com/COVESA/dlt-viewer/commit/63c4f8cedee7b216602fbdb97ba6a47ca34f7315 due to thrown exception when uninteresting control message type is encountered. This change fixes the regression by not throwing an exception in parse-method. The method now returns "uninteresting"-payload.
See https://github.com/COVESA/dlt-viewer/discussions/642
> Avoid exception when parsing uninteresting control message

- qdlt/tests/CMakeLists.txt
- qdlt/tests/test_qdltargument.cpp
Add first unit tests for QDltArgument class focussing on utf8/ascii strings.
> tests: add unit test for QDltArgument

- qdlt/qdltctrlmsg.cpp
- qdlt/qdltctrlmsg.h
- src/mainwindow.cpp
GetSoftwareVersion ctrl message does not encode
string length in the payload
Additionally, protect parsing function
with try-catch
See
https://github.com/COVESA/dlt-viewer/discussions/642
> fix crash due to wrongly parsed ctrl message

- .github/workflows/BuildPR.yml
- .github/workflows/Release.yml
- build_config.bat
Change windows 2019 to windows 2025. Will impact both PR and Release workflows.
This is due to Github no longer supporting Windows 2019
> Windows 2019 to latest

- qdlt/qdltargument.cpp
- qdlt/tests/test_qdltargument.cpp
This is to address https://github.com/COVESA/dlt-viewer/issues/657
I partially reverted two commits (added recently for 2.28) that started to interpret string arguments with ASCII encoding (`DltTypeInfoStrg`) as Latin1-encoded strings. Previously, dlt-viewer interpreted the same way both ASCII and UTF8 args, both were assumed UTF8. This PR restores that legacy behavior that many users relied upon for years, even if it is not 100% correct.
> Restore string arg encoding 

- .github/workflows/BuildPR.yml
Replacing macOS 13 with macos-15-intel
Replaced xCode 15.2 with 26.0
macOS 13 runner is going EOL 12/4/25.
intel x86_64 will be EOL Fall 2027
> Replace x86_64 macOS build
